#!/usr/bin/env bash
set -e

REPO_URL="https://github.com/Ciddarth-raaj/dnds-gofrugal-synker.git"
REPO_NAME="dnds-gofrugal-synker"

# --- Determine repo root (for both init and update) ---
get_repo_root() {
  if [[ -f "ecosystem.config.cjs" ]]; then
    echo "$(pwd)"
    return
  fi
  if [[ -d "$REPO_NAME" && -f "$REPO_NAME/ecosystem.config.cjs" ]]; then
    echo "$(pwd)/$REPO_NAME"
    return
  fi
  echo ""
}

# --- Prompt for a value with optional default ---
prompt_env() {
  local key="$1"
  local default="$2"
  local secret="${3:-0}"
  local val=""
  if [[ -n "$default" ]]; then
    if [[ "$secret" == "1" ]]; then
      read -r -p "$key [$default]: " val
    else
      read -r -p "$key [$default]: " val
    fi
    echo "${val:-$default}"
  else
    read -r -p "$key: " val
    echo "$val"
  fi
}

# --- Create root .env from prompts ---
create_root_env() {
  local dir="$1"
  echo "Creating root .env (press Enter to accept default when shown)."
  PORT=$(prompt_env "PORT" "9003")
  FRONTEND_PORT=$(prompt_env "FRONTEND_PORT" "9004")
  MSSQL_USER=$(prompt_env "MSSQL_USER" "sa")
  MSSQL_PASSWORD=$(prompt_env "MSSQL_PASSWORD" "your_password" "1")
  MSSQL_SERVER=$(prompt_env "MSSQL_SERVER" "DN13")
  MSSQL_INSTANCE=$(prompt_env "MSSQL_INSTANCE" "GFT")
  MSSQL_DATABASE=$(prompt_env "MSSQL_DATABASE" "master")
  MSSQL_ENCRYPT=$(prompt_env "MSSQL_ENCRYPT" "false")
  MSSQL_TRUST_SERVER_CERTIFICATE=$(prompt_env "MSSQL_TRUST_SERVER_CERTIFICATE" "true")
  GOFRUGAL_SYNKER_BASE_URL=$(prompt_env "GOFRUGAL_SYNKER_BASE_URL" "http://localhost:8080")
  SYNC_BATCH_SIZE=$(prompt_env "SYNC_BATCH_SIZE" "5000")
  IS_DEV=$(prompt_env "IS_DEV" "false")
  DEV_TABLES_JSON=$(prompt_env "DEV_TABLES_JSON" "config/dev-tables.json")

  cat > "$dir/.env" << ENVEOF
# Backend server port (default 3080)
PORT=$PORT

# Frontend port when run separately with PM2 (serve built app; default 3000)
FRONTEND_PORT=$FRONTEND_PORT

# SQL Server (GoFrugal source)
MSSQL_USER=$MSSQL_USER
MSSQL_PASSWORD=$MSSQL_PASSWORD
MSSQL_SERVER=$MSSQL_SERVER
MSSQL_INSTANCE=$MSSQL_INSTANCE
MSSQL_DATABASE=$MSSQL_DATABASE
MSSQL_ENCRYPT=$MSSQL_ENCRYPT
MSSQL_TRUST_SERVER_CERTIFICATE=$MSSQL_TRUST_SERVER_CERTIFICATE

# Gofrugal Synker API (dailyneeds-store-backend)
GOFRUGAL_SYNKER_BASE_URL=$GOFRUGAL_SYNKER_BASE_URL

# Optional: max rows per sync request (default 5000)
SYNC_BATCH_SIZE=$SYNC_BATCH_SIZE

# Dev mode: no SQL Server; use dummy table config/data from JSON (default false)
IS_DEV=$IS_DEV
# Path to dev tables JSON when IS_DEV=true (relative to project root)
DEV_TABLES_JSON=$DEV_TABLES_JSON
ENVEOF
  echo "Wrote $dir/.env"
}

# --- Create frontend .env so VITE_API_URL is set for build ---
create_frontend_env() {
  local dir="$1"
  local backend_port="$2"
  local vite_api_url="http://localhost:${backend_port}"
  mkdir -p "$dir/frontend"
  echo "# Generated by deploy.sh - API URL for built frontend" > "$dir/frontend/.env"
  echo "VITE_API_URL=$vite_api_url" >> "$dir/frontend/.env"
  echo "Wrote $dir/frontend/.env (VITE_API_URL=$vite_api_url)"
}

# --- Init: clone, install, prompt .env, build, pm2 start ---
cmd_init() {
  local target_dir
  if [[ -d "$REPO_NAME" ]]; then
    echo "Directory $REPO_NAME already exists. Use 'update' or remove it first."
    exit 1
  fi
  echo "Cloning $REPO_URL into ./$REPO_NAME ..."
  git clone "$REPO_URL" "$REPO_NAME"
  target_dir="$(pwd)/$REPO_NAME"
  cd "$target_dir"

  create_root_env "$target_dir"
  backend_port=$(grep -E '^PORT=' "$target_dir/.env" | cut -d= -f2)
  [[ -z "$backend_port" ]] && backend_port=9003
  create_frontend_env "$target_dir" "$backend_port"

  echo "Installing dependencies (root)..."
  npm install
  echo "Installing and building frontend..."
  (cd frontend && npm install && npm run build)

  if ! command -v pm2 &> /dev/null; then
    echo "PM2 is not installed. Install with: npm install -g pm2"
    exit 1
  fi
  echo "Starting PM2..."
  pm2 start ecosystem.config.cjs
  echo "Init complete. Backend and frontend are running under PM2."
  pm2 list
}

# --- Update: pull, install, build, pm2 update ---
cmd_update() {
  local root
  root=$(get_repo_root)
  if [[ -z "$root" ]]; then
    echo "Run this script from the repo root (where ecosystem.config.cjs is) or from the directory that contains $REPO_NAME."
    exit 1
  fi
  cd "$root"
  echo "Pulling latest changes..."
  git pull
  echo "Installing dependencies (root)..."
  npm install
  echo "Installing and building frontend..."
  (cd frontend && npm install && npm run build)
  if ! command -v pm2 &> /dev/null; then
    echo "PM2 is not installed. Install with: npm install -g pm2"
    exit 1
  fi
  echo "Restarting PM2 (stop then start for a clean frontend)..."
  pm2 delete gofrugaldbsynker-backend gofrugaldbsynker-frontend 2>/dev/null || true
  pm2 start ecosystem.config.cjs
  echo "Update complete."
  pm2 list
}

# --- Main ---
case "${1:-}" in
  init)
    cmd_init
    ;;
  update)
    cmd_update
    ;;
  *)
    echo "Usage: $0 <init|update>"
    echo "  init   - Clone repo, prompt for .env, install, build, and start with PM2"
    echo "  update - Pull latest, install, build, and reload PM2"
    exit 1
    ;;
esac
